### PR TITLE
Refresh app appearance to match design of web application

### PR DESCRIPTION
**Pull request by mathebox**
### Proposed Changes:
- Use large navigation bar titles
- Color navigation bar in primary brand color
- Use primary brand color instead of default red in some places
- Style calendar view to match navigation bar (inactive today highlight is not perfect)

### CODE REVIEW

**Comment by janrenz** [comment]
can you add a screenshot?

**Comment by mathebox** [comment]
GitHawk Upload by mathebox

**Comment by janrenz** [comment]
Nice

**Review by Einh06 — APPROVED** [review]
Looks good to me.

**Comment by mathebox** [comment]
We are waiting for Mona's feedback on this redesign

**Pull request merged**
