### PR TITLE
Add button for test logins

### PR DESCRIPTION
**Pull request by mathebox**
Fixes https://ticketsystem.schul-cloud.org/browse/IOS-5

- Add button for test logins
- Store credentials in brand configuration
- Simply file decoding of brand structure

### CODE REVIEW

**Comment by Einh06** [comment]
I would make the test accounts optional, so you don't have to include them on release build. I think these credential shouldn't be include in the appstore build for security reasons. Apart from that, looks good to me.

**Review by Einh06 — CHANGES_REQUESTED** [review]
Please make the test account optionals so that you dont have to include them on appstore build

**Comment by mathebox** [comment]
@Einh06 The credentials are similar to the one used on the website. They allow users who are interested to get a glimpse of the system. Since they are included in plain text on the website, these credentials can be considered as publicly known.

**Comment by Einh06** [comment]
Ok Fair enough

**Review by Einh06 — APPROVED** [review]

**Pull request merged**
